services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    networks:
      - app-net

  clickhouse:
    image: clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: always
    networks:
      - app-net

  redis: 
    image: redis:latest
    ports:
      - "36379:6379"
    environment:
      - REDIS_PASSWORD=123654789
    restart: always
    networks:
      - app-net

volumes:
  mysql-data:
  clickhouse-data:
  redis-data:

networks:
  app-net:
    driver: bridge
