services:
  php:
    build:
      context: .
      dockerfile: ./configs/php/default.Dockerfile
    volumes:
      - ./datas/php:/www #only for test
      # - data_www:/www
    working_dir: /www
    tty: true
    ports:
      - "9000:9000"
      - "9003:9003" # xdebug
    networks:
      - php-net

  nginx: 
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/php/nginx/nginx-php.conf:/etc/nginx/conf.d/default.conf
      - ./configs/php/nginx/cert:/etc/nginx/cert
    working_dir: /data
    tty: true
    networks:
      - php-net

volumes:
  data_www:

networks:
  php-net:
    driver: bridge
